In [1]:
!nvidia-smi

Tue Jun 17 09:59:43 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.77.01              Driver Version: 566.36         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...    On  |   00000000:01:00.0  On |                  N/A |
| N/A   48C    P3             17W /   74W |    1649MiB /   8188MiB |      7%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

2.6.0+cu124


In [3]:
# create a tensor
some_tensor = torch.rand(3, 4, device=device)
some_tensor

tensor([[0.1417, 0.1592, 0.3577, 0.6536],
        [0.9371, 0.4240, 0.5590, 0.2632],
        [0.6260, 0.9445, 0.1339, 0.2139]], device='cuda:0')

In [4]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1417, 0.1592, 0.3577, 0.6536],
        [0.9371, 0.4240, 0.5590, 0.2632],
        [0.6260, 0.9445, 0.1339, 0.2139]], device='cuda:0')
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cuda:0


In [5]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [7]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [8]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [9]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [10]:
torch.argmax(x)

tensor(9)

In [11]:
torch.argmin(x)

tensor(0)

In [12]:
x = torch.arange(1, 10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x_reshaped = x.reshape(9, 1)
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [14]:
z = x.view(1,9)
z

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [15]:
z[:, 0] = 69
z, x

(tensor([[69,  2,  3,  4,  5,  6,  7,  8,  9]]),
 tensor([69,  2,  3,  4,  5,  6,  7,  8,  9]))

In [16]:
x[0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [22]:
RANDOM_SEED = 23

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 5)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 5)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.4283, 0.2889, 0.4224, 0.3571, 0.9577],
        [0.1100, 0.2933, 0.9205, 0.5876, 0.1299],
        [0.6729, 0.1028, 0.7876, 0.5540, 0.4653]])
tensor([[0.4283, 0.2889, 0.4224, 0.3571, 0.9577],
        [0.1100, 0.2933, 0.9205, 0.5876, 0.1299],
        [0.6729, 0.1028, 0.7876, 0.5540, 0.4653]])
tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])


In [23]:
torch.cuda.device_count()

1